### ISSUE TITLE
No Ivy distribution available for use with Angular 13

### ISSUE THREAD

**Issue by internalsystemerror** [JsDaddy/ngx-mask#949] opened 2021-11-23 10:49 UTC
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Building using Angular 12 generates no warnings/errors. Upgrading to Angular 13 does however.

### Description

 A clear and concise description of the problem...

After upgrading to Angular 13, build now generates these warnings for this package:

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

```
ng new
ng add ngx-mask
ng build
```

## 🔥 Exception or Error

```
 Compiling with Angular sources in Ivy partial compilation mode.Processing legacy "View Engine" libraries:
- ngx-mask [es2015/esm2015] (git@github.com:JsDaddy/ngx-mask.git)
Encourage the library authors to publish an Ivy distribution.
```

## 🌍 Your Environment

**Angular Version:**

```
Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: yarn 1.22.17
OS: linux x64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
ng-packagr                      13.0.6
rxjs                            7.4.0
typescript                      4.4.4
```

**Anything else relevant?**

**Comment by NepipenkoIgor** [comment] 2022-09-11 12:39
@internalsystemerror  Hi . Thank you that using our package .  If you are still has a problem or interesting in it please provide 
example  in stackblitz. 
Also i just created simple one https://stackblitz.com/edit/angular-material-13-starter-x1xj4z-zdgpnn?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

and everything without error . 

I close this issues because we cant reproduce

**Closed by NepipenkoIgor** 2022-09-11 12:39 UTC
