### ISSUE TITLE
Backspace Not Working With Phone Number Mask in Edge

### ISSUE THREAD

**Issue by CoreyAdler** [JsDaddy/ngx-mask#461] opened 2019-05-06 15:06 UTC
I have an input with a mask of (000) 000-0000 (standard US phone number mask). The backspace works perfectly fine in Chrome and Firefox. In Edge, however, the backspace gets stuck on the space after the ). Only moving the cursor to the ) and then pressing backspace works.

I'm working off of version 7.9.6 where this is happening.

**Comment by ValeriaKochegarova** [comment] 2019-05-07 10:57
Duplicate of #417

**Closed** 2019-05-07 13:26 UTC
Labels: P2, bug, duplicate, help wanted

**Comment by Serge0111** [comment] 2019-05-07 15:02
hi @CoreyAdler, try new version it should work.
