### ISSUE TITLE
version 7.9.8 doesnt works in IE 11

### ISSUE THREAD

**Issue by rakeshnayak360** [JsDaddy/ngx-mask#465] opened 2019-05-08 09:32 UTC
I updated the version to 7.9.8 from 7.3.6. Masking is not working in IE 11.
[ I added polyfills core-js to my angular project.]

**Comment by NepipenkoIgor** [comment] 2019-05-08 09:44
@rakeshnayak360 Could you provide error message ? And how you add polyfills ? Do you use angular-cli ?

**Comment by rakeshnayak360** [comment] 2019-05-08 10:09
I am not getting any error. In chrome it works fine but in IE it doesnt.
I used angular-cli
steps i followed to add pollyfill.
1. In polyfills.ts , i uncommented following lines
import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';

then i uncommented  import 'classlist.js'; line and installed classlist.js using npm install --save classlist.js

then  i uncommented  import 'core-js/es6/reflect'; 

then i uncommented  import 'web-animations-js'; line and installed  using npm install --save web-animations-js

then uncommented import 'zone.js/dist/zone'; line

**Comment by AlexeyDolya** [comment] 2019-05-08 11:27
@rakeshnayak360 look 
Duplicate of #425 or #337

**Closed** 2019-05-08 11:27 UTC
Labels: browser: IE, help wanted
