### ISSUE TITLE
Angular 5.0.1 -- Possible Bug

### ISSUE THREAD

**Issue by ThalesMatoso** [JsDaddy/ngx-mask#49] opened 2017-11-13 01:51 UTC
When in the html is inserted the mask, I have this error that does not let my component be loaded, linking to another InjectionToken error, and when I remove the mask everything works.

below the image of the same.

Erro no HTML
![captura de tela de 2017-11-12 23-47-30](https://user-images.githubusercontent.com/20910274/32706350-1a66f39e-c804-11e7-9735-4bd640bd4e7c.png)

InjectionToken
![captura de tela de 2017-11-12 23-49-47](https://user-images.githubusercontent.com/20910274/32706370-3a6a7ad0-c804-11e7-899d-c4bf9c403a5f.png)

**Comment by NepipenkoIgor** [comment] 2017-11-13 19:38
@ThalesMatoso Thank you . I will check

**Comment by ThalesMatoso** [comment] 2017-11-13 23:01
Ok, waiting, I believe is @angular/http has to be deprecated is you using in app.module, but I do not know working on plugin ...

has prevision? my project have dependecy on plugin

Sorry my english, I'm training whitout translator.

**Comment by NepipenkoIgor** [comment] 2017-11-22 19:04
@ThalesMatoso Сould you provide  more info or make some test project?

**Comment by ThalesMatoso** [comment] 2017-11-23 12:50
i try insert mask at input text, after update angular 5, all librarys work with success, exception ngx-mask

I remove mask at input text bellow and project well its work fine
`mask="00.000.000/0000`

**Comment by caseyPav** [comment] 2017-11-24 20:25
@ThalesMatoso @NepipenkoIgor  I've spent a now disgusting amount of time trying to figure out what was breaking my app... see the post above for some detail... I think the fix is straightforward and will take a look at it after confirming all else is functional now that my app loads again... will update this post shortly

**Comment by ThalesMatoso** [comment] 2017-11-25 19:49
Good, i try again reinstall plugin on my project after update to 2.1.17, but not have success.

follow  more details below
Version Plugin 2.1.17
![captura de tela de 2017-11-25 17-30-24](https://user-images.githubusercontent.com/20910274/33234060-4e717c6a-d207-11e7-8d41-e15a50772146.png)

After update with npm install
![captura de tela de 2017-11-25 17-35-12](https://user-images.githubusercontent.com/20910274/33234067-7367cff6-d207-11e7-8a5b-f075e14e3c8f.png)

Error on console and mask-service.js
![captura de tela de 2017-11-25 17-29-16](https://user-images.githubusercontent.com/20910274/33234070-97ec338a-d207-11e7-8b8b-3ea86f1d71d6.png)

it is error on mask-service.js
![captura de tela de 2017-11-25 17-28-50](https://user-images.githubusercontent.com/20910274/33234094-dffbb380-d207-11e7-8821-01fa67a703ab.png)

is my organization.component.html
![captura de tela de 2017-11-25 17-29-42](https://user-images.githubusercontent.com/20910274/33234107-03a58892-d208-11e7-9c6d-1246929cc575.png)



Sorry but not have installed @angular/http, because angular 5 is deprecated. But is necessary or am i mistaki?

Thank you for attention.

**Comment by vgildeev** [comment] 2017-11-28 12:40
Hi, I'm experiencing the same problem with `Cannot read property 'map' of undefined`. It's working fine in JIT mode but failed in AOT mode.
I'm using `angular v5.0.2` along with reactive forms and running my project with this command: `ng serve --aot`.
Cannot provide test project because I didn't find any online editor which allows me to run angular app in aot mode.

**Comment by ThalesMatoso** [comment] 2017-11-29 10:39
@caseyPav not got it, more details please?

**Comment by caseyPav** [comment] 2017-11-29 20:52
@ThalesMatoso I don't have much to add sadly- when built AOT the config injectiontoken is always undefined, which causes the app to break. In AOT the default or specified masking rules never get set as they are not being passed.

**Comment by ThalesMatoso** [comment] 2017-11-30 20:06
I agree, but aot on new version Angular aot is default. i dont  know how to do. Solutions?

**Comment by vgildeev** [comment] 2017-12-01 17:05
I've forked this lib and fixed this issue. Here you can see a [fix](https://github.com/vgildeev/ngx-mask/commit/064a071716a5c433c07d4091de696fa170a49059) just in case you might need it too :).

**Comment by caseyPav** [comment] 2017-12-01 18:14
@vgildeev Thanks so much! I was frustratingly close in my attempted fix! 

@NepipenkoIgor would you consider implementing this fix? resolves all AOT issues on my end as well

**Comment by digitalmedia34** [comment] 2017-12-04 20:29
I can confirm that resolved the AOT and Prod flag issue on my end as well

**Comment by digitalmedia34** [comment] 2017-12-06 22:50
Maybe we should keep this open until the fixes get merged into master branch,  for visibility purpose.

**Comment by Shadayy** [comment] 2018-01-02 18:43
@NepipenkoIgor This issue is closed but the solution @vgildeev gave still not implemented in this repo.

**Comment by NepipenkoIgor** [comment] 2018-01-02 19:53
@Shadayy Thanks , i will try  reproduce @vgildeev problem

**Comment by Shadayy** [comment] 2018-01-02 19:59
@NepipenkoIgor I fixed this issue by doing NgxMaskModule.forRoot() in my app.module (it was missing the .forRoot() ).
I'm running the 2.2.2 version

**Comment by NepipenkoIgor** [comment] 2018-01-02 20:04
@Shadayy Awesome, then think i can close this issue

**Closed by NepipenkoIgor** 2018-01-02 20:04 UTC

**Comment by ritwickdey** [comment] 2018-07-17 10:57
I'm getting the same issue. in `^2.4.4` 

If I provide `MaskService` in component level, the error is gone. If I provide `MaskService` sub module or root module level, I'm getting same error. 

[Note: I'm using lazy loading]
