### ISSUE TITLE
How to stop keypress when cursor is at the end of the text box

### ISSUE THREAD

**Issue by rakeshnayak360** [JsDaddy/ngx-mask#464] opened 2019-05-08 09:09 UTC
When the cursor is at end of the textbox, masking is allowing to type. How to avoid it. Screen shot given below.

![image](https://user-images.githubusercontent.com/19386889/57363584-00e11300-719f-11e9-9253-408a7f62f8e7.png)

**Comment by AlexeyDolya** [comment] 2019-05-08 09:15
please provide the code example

**Comment by rakeshnayak360** [comment] 2019-05-08 09:41
HTML:
mask="000-000000-000" showMaskTyped="true"

**Comment by AlexeyDolya** [comment] 2019-05-08 10:52
@rakeshnayak360 
Duplicate of #235

**Closed** 2019-05-08 10:52 UTC
Labels: question
